
import { Geist, Geist_Mono, Albert_Sans } from "next/font/google";
import "./globals.css";
import { useContext } from "react";
import Header from "@/components/Header";
import { AppContextProvider } from "@/context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppContextProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${albertSans.variable} bg-gray-200 text-gray-800`}>
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          <footer className="text-center py-6 text-sm text-gray-500">2025 NextEstate</footer>
        </body>
      </html >
    </AppContextProvider>
  );
}
